import { Client } from "@/types/client";
export const clientsData: Client[] = [
  {
    id: 1,
    title: "casrilnka",
    logo: "/images/clientLogo/casrilnka.jpg",
    logoWhite: "/images/brands/graygrids-white.svg",
    link: "#",
  },
  {
    id: 2,
    title: "dentalpro",
    logo: "/images/clientLogo/dentalpro.png",
    logoWhite: "/images/brands/lineicons-white.svg",
    link: "#",
  },
  {
    id: 3,
    title: "pasg",
    logo: "/images/clientLogo/pasg.png",
    logoWhite: "/images/brands/uideck-white.svg",
    link: "#",
  },
  {
    id: 4,
    title: "solor",
    logo: "/images/clientLogo/solor.png",
    logoWhite: "/images/brands/ayroui-white.svg",
    link: "#",
  },
  {
    id: 5,
    title: "vyper",
    logo: "/images/clientLogo/vyper.png",
    logoWhite: "/images/brands/tailgrids-white.svg",
    link: "#",
  },
  {
    id: 6,
    title: "Pak",
    logo: "/images/clientLogo/pak.png",
    logoWhite: "/images/brands/tailgrids-white.svg",
    link: "#",
  },
  {
    id: 7,
    title: "Pak",
    logo: "/images/clientLogo/beatech-feature.webp",
    logoWhite: "/images/brands/tailgrids-white.svg",
    link: "#",
  },
  {
    id: 8,
    title: "Pak",
    logo: "/images/clientLogo/ikman.webp",
    logoWhite: "/images/brands/tailgrids-white.svg",
    link: "#",
  },
  {
    id: 9,
    title: "Pak",
    logo: "/images/clientLogo/NBR-Feature.webp",
    logoWhite: "/images/brands/tailgrids-white.svg",
    link: "#",
  },
];
